FROM ubuntu:18.04

COPY common.sh /
RUN /common.sh

COPY xargo.sh /
RUN /xargo.sh

COPY cmake.sh /
RUN apt-get purge --auto-remove -y cmake && \
    /cmake.sh

RUN apt-get install -y --no-install-recommends \
    g++ \
    zlib1g-dev \
    wget unzip ca-certificates

RUN mkdir -p /opt/protobuf/21.12 && \
    cd /opt/protobuf/21.12 && \
    wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip && \
    unzip protoc.zip && \
    rm protoc.zip && \
    ln -s /opt/protobuf/21.12/bin/protoc /usr/bin/protoc

ENV PROTOC=/opt/protobuf/21.12/bin/protoc

COPY qemu.sh /
RUN /qemu.sh x86_64 softmmu

COPY dropbear.sh /
RUN /dropbear.sh

COPY linux-image.sh /
RUN /linux-image.sh x86_64

COPY linux-runner /

ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner x86_64"
